name: PR checks

on:
  pull_request:
  push:
    branches: master

jobs:
  swiftformat-lint:
    uses: Cyberbeni/workflows/.github/workflows/swiftformat-lint.yml@master
  swift-test:
    uses: Cyberbeni/workflows/.github/workflows/swift-test.yml@master
